name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-sdl3:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
      with:
         submodules: recursive
    - name: Build
      run: | 
          cd SDL
          cmake -S . -B build 
          cmake --build build 
          sudo cmake --install build --prefix /usr/local/sdl3
    - name: Move so sdl files to respective folders
      run: |
        cd "$GITHUB_WORKSPACE"
        mkdir -p "$GITHUB_WORKSPACE/lib/sdl3"
        mkdir -p "$GITHUB_WORKSPACE/bin/sdl3"
        sudo mv /usr/local/sdl3/lib/* "$GITHUB_WORKSPACE/lib/sdl3/" 
        sudo mv /usr/local/sdl3/bin/* "$GITHUB_WORKSPACE/bin/sdl3/"

        
  test-server:

    runs-on: ubuntu-24.04-arm
    needs: build-sdl3

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin server --verbose
    - name: Run tests
      run: cargo test --verbose
      
  test-client:

    runs-on: ubuntu-24.04-arm
    needs: build-sdl3

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --bin client --verbose
    - name: Run tests
      run: cargo test --verbose

